# 以太坊配置
ethereum:
  # 节点URL
  # 根据环境配置节点URL
  # 本地开发环境使用 localhost
  # 测试网络使用相应的测试网URL
  # 主网使用主网节点URL
  node_url: "${ETHEREUM_NODE_URL:-http://localhost:8545}"
  # ABI文件路径
  abi_path: "D:/work/gitspace/web3/web3/hardhat-project/artifacts/contracts"
  # 合约绑定输出路径
  bindings_path: "abi/bindings"
  # 默认账户私钥（Hardhat默认的第一个账户）
  private_key: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

# 合约配置
contracts:
  # 部署合约时发送的ETH数量
  lock_value: "1.0"
  purchase_value: "2.0"
  # 拍卖时间（秒）
  auction_time: 3600
  # 锁定时间（秒）
  lock_time: 3600 