server:
    port: 8080
    mode: debug  # debug or release
    read_timeout: 60
    write_timeout: 60
    max_header_bytes: 1048576  # 1MB
    base_path: "/api"

ethereum:
    networks:
        local:
            network_name: local
            rpc_url: http://localhost:8545
            ws_url: ws://localhost:8545
            chain_id: 1337
            accounts:
                default:
                    private_key: "0x9c5c5385611ea8b477fd47f610879f75c95b0b59d38ff53607fa9da75c04959b"
                    address: "0x3353DA979dB07573819F3f9bc6fb5F6D9A057ED2"
                alice:
                    private_key: "0xdb75c2aa35d47eb92b7ccb781001587ddb74565b3bf2f09ca0c9ecf3b3368e52"
                    address: "0x4696a1cD276559aF0A2237012AfE35257d3760c3"
                bob:
                    private_key: "0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890"
                    address: "0x35E386579964B3b62158D7A97a750e484a7D97Be"
            contracts:
                simple_storage:
                    address: ""
                    abi: "SimpleStorage.json"
                lock:
                    address: ""
                    abi: "Lock.json"
                shipping:
                    address: ""
                    abi: "Shipping.json"
                simple_auction:
                    address: ""
                    abi: "SimpleAuction.json"
                array_demo:
                    address: ""
                    abi: "ArrayDemo.json"
        mainnet:
            network_name: "Mainnet"
            rpc_url: "https://mainnet.infura.io/v3/YOUR-PROJECT-ID"
            ws_url: "wss://mainnet.infura.io/ws/v3/YOUR-PROJECT-ID"
            chain_id: 1
            accounts: {}
            contracts: {}
        sepolia:
            network_name: "Sepolia"
            rpc_url: "https://sepolia.infura.io/v3/6174f2eb846e40ac97d70174693afb97"
            ws_url: "wss://sepolia.infura.io/ws/v3/6174f2eb846e40ac97d70174693afb97"
            chain_id: 11155111
            accounts: {}
            contracts: {}

log:
    level: "debug"
    filename: "web3.log"
